############# English navigation ##############

# main menu
[[main]]
name = "About us"
pageRef = "/about"
weight = 1

[[main]]
name = "Resources"
pageRef = "/about"
weight = 4 

[[main]]
name = "Technical support"
pageRef = "/elements"
weight = 6

[[main]]
name = "Forum"
pageRef = "/elements"
weight = 5

[[main]]
name = "Calculator"
pageRef = "/post-3-on.md"
weight = 3 

[[main]]
name = "What is One Health?"
pageRef = "/blog"
weight = 2

[[main]]
weight = 1
name = "Resources"

[[main]]
parent = "Technical support"
name = "FAQs"
pageRef = "/FAQs-1"

[[main]]
parent = "Technical support"
name = "Contact us"
pageRef = "/contact"

[[main]]
parent = "Forum"
name = "Discussion forum"
pageRef = "/"

[[main]]
parent = "Resources"
name = "Downloadable resources"
pageRef = "/Downloadable_resources"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Contact us"
pageRef = "/contact"
weight = 2

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 3
