############# English navigation ##############

# main menu
[[main]]
name = "About us"
pageRef = "/about"
weight = 1

[[main]]
name = "Resources"
pageRef = "/about"
weight = 3

[[main]]
name = "Technical support"
pageRef = "/elements"
weight = 5

[[main]]
name = "Forum"
pageRef = "/elements"
weight = 4

[[main]]
name = "What is One Health?"
pageRef = "/Understanding-one-health"
weight = 2

[[main]]
weight = 1
name = "Resources"

[[main]]
parent = "Resources"
name = "Understanding One Health"
pageRef = "/blog"

[[main]]
parent = "Resources"
name = "Research and publications"
pageRef = "/research-publications"

[[main]]
parent = "Technical support"
name = "FAQs"
pageRef = "/FAQs-1"

[[main]]
parent = "Forum"
name = "Discussion forum"
pageRef = "/"

[[main]]
parent = "Resources"
name = "Downloadable resources"
pageRef = "/Downloadable_resources"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Contact us"
pageRef = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 4
